[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [{ name = "Sanchit Ram Arvind", email = "sanchitram@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "python-multipart>=0.0.6",
    "python-dateutil>=2.8.2",
]
